//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juntos.WcfServiceApp.PagamentoServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PagamentoServices.IPagamentoWService")]
    public interface IPagamentoWService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoWService/Pagar", ReplyAction="http://tempuri.org/IPagamentoWService/PagarResponse")]
        bool Pagar(decimal valor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagamentoWServiceChannel : Juntos.WcfServiceApp.PagamentoServices.IPagamentoWService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagamentoWServiceClient : System.ServiceModel.ClientBase<Juntos.WcfServiceApp.PagamentoServices.IPagamentoWService>, Juntos.WcfServiceApp.PagamentoServices.IPagamentoWService {
        
        public PagamentoWServiceClient() {
        }
        
        public PagamentoWServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagamentoWServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagamentoWServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagamentoWServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Pagar(decimal valor) {
            return base.Channel.Pagar(valor);
        }
    }
}
