//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juntos.aplicacao.Services.proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxy.IPagamentoService")]
    public interface IPagamentoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/Pagar", ReplyAction="http://tempuri.org/IPagamentoService/PagarResponse")]
        bool Pagar(decimal valor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagamentoServiceChannel : Juntos.aplicacao.Services.proxy.IPagamentoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagamentoServiceClient : System.ServiceModel.ClientBase<Juntos.aplicacao.Services.proxy.IPagamentoService>, Juntos.aplicacao.Services.proxy.IPagamentoService {
        
        public PagamentoServiceClient() {
        }
        
        public PagamentoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagamentoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagamentoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagamentoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Pagar(decimal valor) {
            return base.Channel.Pagar(valor);
        }
    }
}
