//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.17626
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juntos.WcfServiceApp.PagamentoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PagamentoService.IPagamentoService")]
    public interface IPagamentoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/Pagar", ReplyAction="http://tempuri.org/IPagamentoService/PagarResponse")]
        bool Pagar(decimal valor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagamentoServiceChannel : Juntos.WcfServiceApp.PagamentoService.IPagamentoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagamentoServiceClient : System.ServiceModel.ClientBase<Juntos.WcfServiceApp.PagamentoService.IPagamentoService>, Juntos.WcfServiceApp.PagamentoService.IPagamentoService {
        
        public PagamentoServiceClient() {
        }
        
        public PagamentoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagamentoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagamentoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagamentoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Pagar(decimal valor) {
            return base.Channel.Pagar(valor);
        }
    }
}
