//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsumidorDTO", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Apresentacao.WcfServiceApp.dto", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ConsumidorDTO : ConsoleApplication1.proxy.PessoaDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsoleApplication1.proxy.CompraDTO> ComprasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsoleApplication1.proxy.CompraDTO> Compras {
            get {
                return this.ComprasField;
            }
            set {
                if ((object.ReferenceEquals(this.ComprasField, value) != true)) {
                    this.ComprasField = value;
                    this.RaisePropertyChanged("Compras");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadeDTO", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Apresentacao.WcfServiceApp.dto", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.proxy.EnderecoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.proxy.TelefoneDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.proxy.CompraDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.proxy.CupomDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.proxy.OfertaDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.proxy.PagamentoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.proxy.PessoaDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.proxy.ConsumidorDTO))]
    public partial class EntidadeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoDTO", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Apresentacao.WcfServiceApp.dto", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EnderecoDTO : ConsoleApplication1.proxy.EntidadeDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep {
            get {
                return this.CepField;
            }
            set {
                if ((object.ReferenceEquals(this.CepField, value) != true)) {
                    this.CepField = value;
                    this.RaisePropertyChanged("Cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelefoneDTO", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Apresentacao.WcfServiceApp.dto", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TelefoneDTO : ConsoleApplication1.proxy.EntidadeDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short DDDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short DDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short DDD {
            get {
                return this.DDDField;
            }
            set {
                if ((this.DDDField.Equals(value) != true)) {
                    this.DDDField = value;
                    this.RaisePropertyChanged("DDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short DDI {
            get {
                return this.DDIField;
            }
            set {
                if ((this.DDIField.Equals(value) != true)) {
                    this.DDIField = value;
                    this.RaisePropertyChanged("DDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraDTO", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Apresentacao.WcfServiceApp.dto", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CompraDTO : ConsoleApplication1.proxy.EntidadeDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.proxy.ConsumidorDTO ConsumidorDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsoleApplication1.proxy.CupomDTO> CuponsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsoleApplication1.proxy.PagamentoDTO> PagamentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorTotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.proxy.ConsumidorDTO ConsumidorDto {
            get {
                return this.ConsumidorDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumidorDtoField, value) != true)) {
                    this.ConsumidorDtoField = value;
                    this.RaisePropertyChanged("ConsumidorDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsoleApplication1.proxy.CupomDTO> Cupons {
            get {
                return this.CuponsField;
            }
            set {
                if ((object.ReferenceEquals(this.CuponsField, value) != true)) {
                    this.CuponsField = value;
                    this.RaisePropertyChanged("Cupons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCompra {
            get {
                return this.DataCompraField;
            }
            set {
                if ((this.DataCompraField.Equals(value) != true)) {
                    this.DataCompraField = value;
                    this.RaisePropertyChanged("DataCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsoleApplication1.proxy.PagamentoDTO> Pagamentos {
            get {
                return this.PagamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.PagamentosField, value) != true)) {
                    this.PagamentosField = value;
                    this.RaisePropertyChanged("Pagamentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorTotal {
            get {
                return this.ValorTotalField;
            }
            set {
                if ((this.ValorTotalField.Equals(value) != true)) {
                    this.ValorTotalField = value;
                    this.RaisePropertyChanged("ValorTotal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CupomDTO", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Apresentacao.WcfServiceApp.dto", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CupomDTO : ConsoleApplication1.proxy.EntidadeDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataUtilizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataValidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.proxy.OfertaDTO OfertaDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataUtilizacao {
            get {
                return this.DataUtilizacaoField;
            }
            set {
                if ((this.DataUtilizacaoField.Equals(value) != true)) {
                    this.DataUtilizacaoField = value;
                    this.RaisePropertyChanged("DataUtilizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataValidade {
            get {
                return this.DataValidadeField;
            }
            set {
                if ((this.DataValidadeField.Equals(value) != true)) {
                    this.DataValidadeField = value;
                    this.RaisePropertyChanged("DataValidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.proxy.OfertaDTO OfertaDto {
            get {
                return this.OfertaDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.OfertaDtoField, value) != true)) {
                    this.OfertaDtoField = value;
                    this.RaisePropertyChanged("OfertaDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfertaDTO", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Apresentacao.WcfServiceApp.dto", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OfertaDTO : ConsoleApplication1.proxy.EntidadeDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.proxy.AnuncianteDTO AnuncianteDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CondicoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsoleApplication1.proxy.CupomDTO> CuponsGeradosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataExpiracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInicioValidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataPublicacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataValidadeCuponsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.proxy.EnderecoDTO EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroMaximoCuponsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.proxy.EnumStatusOferta StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCuponsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.proxy.AnuncianteDTO AnuncianteDto {
            get {
                return this.AnuncianteDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnuncianteDtoField, value) != true)) {
                    this.AnuncianteDtoField = value;
                    this.RaisePropertyChanged("AnuncianteDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Condicoes {
            get {
                return this.CondicoesField;
            }
            set {
                if ((object.ReferenceEquals(this.CondicoesField, value) != true)) {
                    this.CondicoesField = value;
                    this.RaisePropertyChanged("Condicoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsoleApplication1.proxy.CupomDTO> CuponsGerados {
            get {
                return this.CuponsGeradosField;
            }
            set {
                if ((object.ReferenceEquals(this.CuponsGeradosField, value) != true)) {
                    this.CuponsGeradosField = value;
                    this.RaisePropertyChanged("CuponsGerados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataExpiracao {
            get {
                return this.DataExpiracaoField;
            }
            set {
                if ((this.DataExpiracaoField.Equals(value) != true)) {
                    this.DataExpiracaoField = value;
                    this.RaisePropertyChanged("DataExpiracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInicioValidade {
            get {
                return this.DataInicioValidadeField;
            }
            set {
                if ((this.DataInicioValidadeField.Equals(value) != true)) {
                    this.DataInicioValidadeField = value;
                    this.RaisePropertyChanged("DataInicioValidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataPublicacao {
            get {
                return this.DataPublicacaoField;
            }
            set {
                if ((this.DataPublicacaoField.Equals(value) != true)) {
                    this.DataPublicacaoField = value;
                    this.RaisePropertyChanged("DataPublicacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataValidadeCupons {
            get {
                return this.DataValidadeCuponsField;
            }
            set {
                if ((this.DataValidadeCuponsField.Equals(value) != true)) {
                    this.DataValidadeCuponsField = value;
                    this.RaisePropertyChanged("DataValidadeCupons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.proxy.EnderecoDTO Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroMaximoCupons {
            get {
                return this.NumeroMaximoCuponsField;
            }
            set {
                if ((this.NumeroMaximoCuponsField.Equals(value) != true)) {
                    this.NumeroMaximoCuponsField = value;
                    this.RaisePropertyChanged("NumeroMaximoCupons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.proxy.EnumStatusOferta Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCupons {
            get {
                return this.ValorCuponsField;
            }
            set {
                if ((this.ValorCuponsField.Equals(value) != true)) {
                    this.ValorCuponsField = value;
                    this.RaisePropertyChanged("ValorCupons");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagamentoDTO", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Apresentacao.WcfServiceApp.dto", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PagamentoDTO : ConsoleApplication1.proxy.EntidadeDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.proxy.EnumFormaPagamento FormaPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.proxy.EnumStatusPagamento StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataPagamento {
            get {
                return this.DataPagamentoField;
            }
            set {
                if ((this.DataPagamentoField.Equals(value) != true)) {
                    this.DataPagamentoField = value;
                    this.RaisePropertyChanged("DataPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.proxy.EnumFormaPagamento FormaPagamento {
            get {
                return this.FormaPagamentoField;
            }
            set {
                if ((this.FormaPagamentoField.Equals(value) != true)) {
                    this.FormaPagamentoField = value;
                    this.RaisePropertyChanged("FormaPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.proxy.EnumStatusPagamento Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaDTO", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Apresentacao.WcfServiceApp.dto", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.proxy.AnuncianteDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.proxy.ConsumidorDTO))]
    public partial class PessoaDTO : ConsoleApplication1.proxy.EntidadeDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CpfCnpjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsoleApplication1.proxy.EnderecoDTO> EnderecosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsoleApplication1.proxy.TelefoneDTO> TelefonesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.proxy.EnumTipoPessoa TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CpfCnpj {
            get {
                return this.CpfCnpjField;
            }
            set {
                if ((this.CpfCnpjField.Equals(value) != true)) {
                    this.CpfCnpjField = value;
                    this.RaisePropertyChanged("CpfCnpj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsoleApplication1.proxy.EnderecoDTO> Enderecos {
            get {
                return this.EnderecosField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecosField, value) != true)) {
                    this.EnderecosField = value;
                    this.RaisePropertyChanged("Enderecos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsoleApplication1.proxy.TelefoneDTO> Telefones {
            get {
                return this.TelefonesField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonesField, value) != true)) {
                    this.TelefonesField = value;
                    this.RaisePropertyChanged("Telefones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.proxy.EnumTipoPessoa Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnuncianteDTO", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Apresentacao.WcfServiceApp.dto")]
    [System.SerializableAttribute()]
    public partial class AnuncianteDTO : ConsoleApplication1.proxy.PessoaDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsoleApplication1.proxy.OfertaDTO> OfertasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsoleApplication1.proxy.OfertaDTO> Ofertas {
            get {
                return this.OfertasField;
            }
            set {
                if ((object.ReferenceEquals(this.OfertasField, value) != true)) {
                    this.OfertasField = value;
                    this.RaisePropertyChanged("Ofertas");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumTipoPessoa", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Model.Enums")]
    public enum EnumTipoPessoa : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fisica = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Juridica = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumStatusOferta", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Model.Enums")]
    public enum EnumStatusOferta : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Criada = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Publicada = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finalizada = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumFormaPagamento", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Model.Enums")]
    public enum EnumFormaPagamento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NaoDefinida = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayPal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PagSeguro = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cartão = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumStatusPagamento", Namespace="http://schemas.datacontract.org/2004/07/Juntos.Model.Enums")]
    public enum EnumStatusPagamento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pendente = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aprovado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejeitado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelado = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxy.IJuntosService")]
    public interface IJuntosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/RetornarTodosConsumidores", ReplyAction="http://tempuri.org/IJuntosService/RetornarTodosConsumidoresResponse")]
        System.Collections.Generic.List<ConsoleApplication1.proxy.ConsumidorDTO> RetornarTodosConsumidores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/ConsultarConsumidorPeloId", ReplyAction="http://tempuri.org/IJuntosService/ConsultarConsumidorPeloIdResponse")]
        ConsoleApplication1.proxy.ConsumidorDTO ConsultarConsumidorPeloId(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/SalvarConsumidor", ReplyAction="http://tempuri.org/IJuntosService/SalvarConsumidorResponse")]
        void SalvarConsumidor(ConsoleApplication1.proxy.ConsumidorDTO consumidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/RetornarTodosAnunciantes", ReplyAction="http://tempuri.org/IJuntosService/RetornarTodosAnunciantesResponse")]
        System.Collections.Generic.List<ConsoleApplication1.proxy.AnuncianteDTO> RetornarTodosAnunciantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/ConsultarAnunciantePeloId", ReplyAction="http://tempuri.org/IJuntosService/ConsultarAnunciantePeloIdResponse")]
        ConsoleApplication1.proxy.AnuncianteDTO ConsultarAnunciantePeloId(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/ConsultarAnunciantePeloEmail", ReplyAction="http://tempuri.org/IJuntosService/ConsultarAnunciantePeloEmailResponse")]
        ConsoleApplication1.proxy.AnuncianteDTO ConsultarAnunciantePeloEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/SalvarAnunciante", ReplyAction="http://tempuri.org/IJuntosService/SalvarAnuncianteResponse")]
        void SalvarAnunciante(ConsoleApplication1.proxy.AnuncianteDTO anunciante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/RetornarTodasOfertasPorAnunciante", ReplyAction="http://tempuri.org/IJuntosService/RetornarTodasOfertasPorAnuncianteResponse")]
        System.Collections.Generic.List<ConsoleApplication1.proxy.OfertaDTO> RetornarTodasOfertasPorAnunciante(long anuncianteid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/ConsultarOfertaPeloId", ReplyAction="http://tempuri.org/IJuntosService/ConsultarOfertaPeloIdResponse")]
        ConsoleApplication1.proxy.OfertaDTO ConsultarOfertaPeloId(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/SalvarOferta", ReplyAction="http://tempuri.org/IJuntosService/SalvarOfertaResponse")]
        void SalvarOferta(ConsoleApplication1.proxy.OfertaDTO oferta, long idConsumidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/RetornarTodasComprasPorConsumidor", ReplyAction="http://tempuri.org/IJuntosService/RetornarTodasComprasPorConsumidorResponse")]
        System.Collections.Generic.List<ConsoleApplication1.proxy.CompraDTO> RetornarTodasComprasPorConsumidor(long consumidorid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/RetornarTodasCompras", ReplyAction="http://tempuri.org/IJuntosService/RetornarTodasComprasResponse")]
        System.Collections.Generic.List<ConsoleApplication1.proxy.CompraDTO> RetornarTodasCompras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/ConsultarCompraPeloId", ReplyAction="http://tempuri.org/IJuntosService/ConsultarCompraPeloIdResponse")]
        ConsoleApplication1.proxy.CompraDTO ConsultarCompraPeloId(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/SalvarCompra", ReplyAction="http://tempuri.org/IJuntosService/SalvarCompraResponse")]
        void SalvarCompra(ConsoleApplication1.proxy.CompraDTO compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/ComprarOferta", ReplyAction="http://tempuri.org/IJuntosService/ComprarOfertaResponse")]
        ConsoleApplication1.proxy.CompraDTO ComprarOferta(long idConsumidor, long idOferta, int quantidadeCupons);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/PagarCompra", ReplyAction="http://tempuri.org/IJuntosService/PagarCompraResponse")]
        void PagarCompra(long idCompra, ConsoleApplication1.proxy.EnumFormaPagamento formaPagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/InformarUsoCupom", ReplyAction="http://tempuri.org/IJuntosService/InformarUsoCupomResponse")]
        void InformarUsoCupom(long idCupom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/PublicarOferta", ReplyAction="http://tempuri.org/IJuntosService/PublicarOfertaResponse")]
        void PublicarOferta(long idOferta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/ListarCuponsNaoUtilizados", ReplyAction="http://tempuri.org/IJuntosService/ListarCuponsNaoUtilizadosResponse")]
        System.Collections.Generic.List<ConsoleApplication1.proxy.CupomDTO> ListarCuponsNaoUtilizados(long ofertaid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/ConsolidarOferta", ReplyAction="http://tempuri.org/IJuntosService/ConsolidarOfertaResponse")]
        System.Collections.Generic.List<ConsoleApplication1.proxy.CupomDTO> ConsolidarOferta(long ofertaid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJuntosService/RetornarTodasOfertas", ReplyAction="http://tempuri.org/IJuntosService/RetornarTodasOfertasResponse")]
        System.Collections.Generic.List<ConsoleApplication1.proxy.OfertaDTO> RetornarTodasOfertas();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJuntosServiceChannel : ConsoleApplication1.proxy.IJuntosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JuntosServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.proxy.IJuntosService>, ConsoleApplication1.proxy.IJuntosService {
        
        public JuntosServiceClient() {
        }
        
        public JuntosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JuntosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JuntosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JuntosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ConsoleApplication1.proxy.ConsumidorDTO> RetornarTodosConsumidores() {
            return base.Channel.RetornarTodosConsumidores();
        }
        
        public ConsoleApplication1.proxy.ConsumidorDTO ConsultarConsumidorPeloId(long id) {
            return base.Channel.ConsultarConsumidorPeloId(id);
        }
        
        public void SalvarConsumidor(ConsoleApplication1.proxy.ConsumidorDTO consumidor) {
            base.Channel.SalvarConsumidor(consumidor);
        }
        
        public System.Collections.Generic.List<ConsoleApplication1.proxy.AnuncianteDTO> RetornarTodosAnunciantes() {
            return base.Channel.RetornarTodosAnunciantes();
        }
        
        public ConsoleApplication1.proxy.AnuncianteDTO ConsultarAnunciantePeloId(long id) {
            return base.Channel.ConsultarAnunciantePeloId(id);
        }
        
        public ConsoleApplication1.proxy.AnuncianteDTO ConsultarAnunciantePeloEmail(string email) {
            return base.Channel.ConsultarAnunciantePeloEmail(email);
        }
        
        public void SalvarAnunciante(ConsoleApplication1.proxy.AnuncianteDTO anunciante) {
            base.Channel.SalvarAnunciante(anunciante);
        }
        
        public System.Collections.Generic.List<ConsoleApplication1.proxy.OfertaDTO> RetornarTodasOfertasPorAnunciante(long anuncianteid) {
            return base.Channel.RetornarTodasOfertasPorAnunciante(anuncianteid);
        }
        
        public ConsoleApplication1.proxy.OfertaDTO ConsultarOfertaPeloId(long id) {
            return base.Channel.ConsultarOfertaPeloId(id);
        }
        
        public void SalvarOferta(ConsoleApplication1.proxy.OfertaDTO oferta, long idConsumidor) {
            base.Channel.SalvarOferta(oferta, idConsumidor);
        }
        
        public System.Collections.Generic.List<ConsoleApplication1.proxy.CompraDTO> RetornarTodasComprasPorConsumidor(long consumidorid) {
            return base.Channel.RetornarTodasComprasPorConsumidor(consumidorid);
        }
        
        public System.Collections.Generic.List<ConsoleApplication1.proxy.CompraDTO> RetornarTodasCompras() {
            return base.Channel.RetornarTodasCompras();
        }
        
        public ConsoleApplication1.proxy.CompraDTO ConsultarCompraPeloId(long id) {
            return base.Channel.ConsultarCompraPeloId(id);
        }
        
        public void SalvarCompra(ConsoleApplication1.proxy.CompraDTO compra) {
            base.Channel.SalvarCompra(compra);
        }
        
        public ConsoleApplication1.proxy.CompraDTO ComprarOferta(long idConsumidor, long idOferta, int quantidadeCupons) {
            return base.Channel.ComprarOferta(idConsumidor, idOferta, quantidadeCupons);
        }
        
        public void PagarCompra(long idCompra, ConsoleApplication1.proxy.EnumFormaPagamento formaPagamento) {
            base.Channel.PagarCompra(idCompra, formaPagamento);
        }
        
        public void InformarUsoCupom(long idCupom) {
            base.Channel.InformarUsoCupom(idCupom);
        }
        
        public void PublicarOferta(long idOferta) {
            base.Channel.PublicarOferta(idOferta);
        }
        
        public System.Collections.Generic.List<ConsoleApplication1.proxy.CupomDTO> ListarCuponsNaoUtilizados(long ofertaid) {
            return base.Channel.ListarCuponsNaoUtilizados(ofertaid);
        }
        
        public System.Collections.Generic.List<ConsoleApplication1.proxy.CupomDTO> ConsolidarOferta(long ofertaid) {
            return base.Channel.ConsolidarOferta(ofertaid);
        }
        
        public System.Collections.Generic.List<ConsoleApplication1.proxy.OfertaDTO> RetornarTodasOfertas() {
            return base.Channel.RetornarTodasOfertas();
        }
    }
}
