//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juntos.aplicacao.wsPagamentoClient.wsProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pagamento", Namespace="http://schemas.datacontract.org/2004/07/juntos.PagamentoService.model")]
    [System.SerializableAttribute()]
    public partial class Pagamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private juntos.aplicacao.wsPagamentoClient.wsProxy.FormaPagamento FormaPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private juntos.aplicacao.wsPagamentoClient.wsProxy.StatusPagamento StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataPagamento {
            get {
                return this.DataPagamentoField;
            }
            set {
                if ((this.DataPagamentoField.Equals(value) != true)) {
                    this.DataPagamentoField = value;
                    this.RaisePropertyChanged("DataPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public juntos.aplicacao.wsPagamentoClient.wsProxy.FormaPagamento FormaPagamento {
            get {
                return this.FormaPagamentoField;
            }
            set {
                if ((this.FormaPagamentoField.Equals(value) != true)) {
                    this.FormaPagamentoField = value;
                    this.RaisePropertyChanged("FormaPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public juntos.aplicacao.wsPagamentoClient.wsProxy.StatusPagamento Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormaPagamento", Namespace="http://schemas.datacontract.org/2004/07/juntos.PagamentoService.model")]
    public enum FormaPagamento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cartao = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayPal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PagSeguro = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusPagamento", Namespace="http://schemas.datacontract.org/2004/07/juntos.PagamentoService.model")]
    public enum StatusPagamento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pendente = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aprovado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejeitado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelado = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsProxy.IControladorPagamentoService")]
    public interface IControladorPagamentoService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControladorPagamentoService/PaymentRequest")]
        void PaymentRequest(juntos.aplicacao.wsPagamentoClient.wsProxy.Pagamento pgto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControladorPagamentoService/GetPaymentResult", ReplyAction="http://tempuri.org/IControladorPagamentoService/GetPaymentResultResponse")]
        juntos.aplicacao.wsPagamentoClient.wsProxy.Pagamento GetPaymentResult(long pagtoid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControladorPagamentoServiceChannel : juntos.aplicacao.wsPagamentoClient.wsProxy.IControladorPagamentoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControladorPagamentoServiceClient : System.ServiceModel.ClientBase<juntos.aplicacao.wsPagamentoClient.wsProxy.IControladorPagamentoService>, juntos.aplicacao.wsPagamentoClient.wsProxy.IControladorPagamentoService {
        
        public ControladorPagamentoServiceClient() {
        }
        
        public ControladorPagamentoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControladorPagamentoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControladorPagamentoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControladorPagamentoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PaymentRequest(juntos.aplicacao.wsPagamentoClient.wsProxy.Pagamento pgto) {
            base.Channel.PaymentRequest(pgto);
        }
        
        public juntos.aplicacao.wsPagamentoClient.wsProxy.Pagamento GetPaymentResult(long pagtoid) {
            return base.Channel.GetPaymentResult(pagtoid);
        }
    }
}
